model:
  loss_control_para:
    loss_name: [ 'out_l1', 'out_cos', 'logits_mse' ]
    loss_scale:
      out_l1: 1
      out_cos: 1
      logits_mse: 30
    temperature: 1
    vit_kd_para:
      student_dims: 768
      teacher_dims: 768
      low_layers_num: 2
      high_layers_num: 1
    normalize: False

trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'ws-l1-cos-logits_mse'
      project: 'CLIPDistillation'
      log_model: false
      group: weight_share
      tags: [ 'weight share', 'loss change' ]