model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model._image_encoder.ImageEncoder
      init_args:
        is_student: True
        tea_transformer_width: 768
        vit_paras:
          input_resolution: 224
          patch_size: 32
          width: 384
          layers: 4
          heads: 12
          output_dim: 512
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    loss_weight: [1, 1, 1, 30]
    t: 2
    model_type: 'image'
#    batch_size: 128


data:
  class_path: TextDataModule
  init_args:
    num_workers: 8
    dataset: '_dataset'
    batch_size: 512
    kwargs:
      data_dir: '/data/pyz/data'
      dataset_name: 'ImageDataset'
      cache_dir: '/data/pyz/data/cache3'
#      train: true



trainer:
  auto_select_gpus: True # If enabled and gpus or devices is an integer, pick available gpus automatically.
  accumulate_grad_batches: 1
  accelerator: 'gpu'
  max_epochs: 50
  min_epochs: 3
  max_steps: -1 # Stop training after this number of steps. Disabled by default (-1). If max_steps = -1 and max_epochs = None, will default to max_epochs = 1000. To enable infinite training, set max_epochs to -1.
  devices: [1, 3]
  precision: 16
#  log
  log_every_n_steps: 100 # How often to log within steps. Default: 50
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: '/data/pyz/res'
      name: 'ImageEncoder'
      version: null
  enable_progress_bar: True # show the progressbar
  check_val_every_n_epoch: 1 # valid after n epoch. If None, validation will be done solely based on the number of training batches, requiring val_check_interval to be an integer value.
#  val_check_interval: 0.5 # check valid with n batch or n * total_batch_num when check_val_every_n_epoch is None
#  callbacks:
  callbacks:
    - class_path: LearningRateMonitor
#    - class_path: EarlyStopping
#      init_args:
#        monitor: 'val/loss'
    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val/acc_top1:.2f}-loss{val/loss}'
        monitor: 'hp_metric/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
  auto_lr_find: True
#  auto_scale_batch_size: 'binsearch'
#  amp_backend: 'apex'  # or native
#  resume_from_checkpoint: '/load/my/checkpoint'
  strategy: 'ddp'
#  Debug
#  limit_train_batches: 0.001
#  limit_val_batches: 0.25 # or int 3 means 3 batches
#  limit_test_batches:
#  fast_dev_run: True
#  limit_predict_batches
#  overfit_batches: 1 # Overfit a fracion of training/validation data (float) or a set number of batches (int). Default: 0.0.t



optimizer:
  class_path: Adam
  init_args:
    lr: 0.0022908676527677745
    weight_decay: 0.0001


lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20