model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model.component.weight_share_model.RepeatTextTransformer
      init_args:
        depth: 4
        repeated_times: 2
        use_transform: True
    norm: False
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'smd' ]
      temperature: 1
      loss_scale:
        out_l1: 1
        out_cos: 1
        smd: 0.02
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    teacher_need_layers: [ 0, 1, 10, 11 ]
    model_type: 'text'
    map_type: 'begin'
    init_type: null
    warm_steps: 20
    total_steps: 500
    weight_decay: 1.0e-2
    lr: 1.0e-3




data:
  class_path: MainDataModule
  init_args:
    num_workers: 16
    dataset: 'text_dataset'
    dataset_name: 'TextDataset'
    train_batch_size: 1024
    val_batch_size: 1250
    dataset_para:
      data_dir: '/data/pyz/data'
      cache_dir: '/data/pyz/.cache'




trainer:
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  accelerator: 'gpu'

  strategy: 'ddp_find_unused_parameters_false'
  max_epochs: 500
  precision: 16
#    limit_train_batches: 1
  log_every_n_steps: 100
  enable_progress_bar: True
  check_val_every_n_epoch: 1


  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name: 'weight-share-text-baseline'
      project: 'CLIPDistillation'
      log_model: false
      group: ws_image_encoder
      tags: [ 'ws_text_encoder' ]


  callbacks:
    - class_path: LearningRateMonitor
    - class_path: EarlyStopping
      init_args:
        monitor: 'val_loss/loss'
        patience: 10

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_stu_acc/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_loss/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false