trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'vit_kd'
      project: '毕设实验'
      log_model: false
      group: ws_image_encoder

model:
  loss_control_para:
    loss_name: [ 'vit_kd', 'out_cos' ]
    need_norm: False
    loss_init_args:
      vit_kd:
        low_layers_num: 1
        high_layers_num: 1
        student_dims: 768
        teacher_dims: 768
