model:
  class_path: DistillModel
  init_args:
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'smd' ]
      loss_scale:
        out_l1: 1
        out_cos: 1
        smd: 0.02

trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'ws-smd_loss'
      project: 'CLIPDistillation'
      log_model: false
      group: ws_image_encoder
      tags: [ 'ws_image_encoder', 'model change', 'loss change' ]