model:
  class_path: DualDistillModel
  init_args:
    image_student:
      class_path: model.component.weight_share_model.RepeatVisionTransformer
      init_args:
        img_size: 224
        patch_size: 32
        in_chans: 3
        out_dim: 512
        embed_dim: 768
        depth: 6
        num_heads: 24
        mlp_ratio: 4.0
        qkv_bias: True
        repeated_times: 2
        use_transform: True
    text_student:
      class_path: model.component.weight_share_model.RepeatTextTransformer
      init_args:
        depth: 4
        repeated_times: 2
        use_transform: True
    load_path:
      image: 'The/path/to/your/image_model.ckpt'
      text: 'The/path/to/your/text_model.ckpt'


    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'cos_diff' ]
      loss_scale:
        cos_diff: 0.1


    download_root: '/data/pyz/.cache'
    warm_steps: 15
    total_steps: 300
    weight_decay: 1.0e-3
    lr: 1.0e-4

data:
  class_path: MainDataModule
  init_args:
    dataset: 'ms_coco'
    dataset_name: 'COCODataset'
    dataset_para:
      root_path: '/home/pyz32/data_tmp/mscoco'
      annotation_path: '/home/pyz32/data_tmp/mscoco/annotations'
    train_batch_size: 512
    val_batch_size: 1250
    num_workers: 12


trainer:
  num_sanity_val_steps: 0
  strategy: 'ddp_find_unused_parameters_false'
  default_root_dir: './'
  accumulate_grad_batches: 1
  accelerator: 'gpu'
  max_epochs: 300
  log_every_n_steps: 15
  enable_progress_bar: True
  check_val_every_n_epoch: 1
  precision: 16
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: './result'
      name: 'L-CLIP'
      project: 'CLIPDistillation'
      log_model: false
      group: clip
      tags: [ 'weight share', 'loss change', 'CLIP model' ]


  callbacks:
    - class_path: LearningRateMonitor

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_stu_acc/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_loss/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false