model:
  class_path: DualDistillModel
  init_args:
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos' ]
      temperature: 2

trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name: 'clip_baseline'
      project: 'CLIPDistillation'
      log_model: false
      group: clip
      tags: [ 'weight share', 'loss change', 'CLIP model' ]