trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name : 'WeightShareDistillation_lr5e-3_wd1e-5'
      project: 'WeightShareDistillation'
      version: null
      log_model: false
      sync_tensorboard: True

model:
  class_path: DistillModel
  init_args:
    lr: 1.0e-5
