model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model.component.image_encoder.ImageEncoder
      init_args:
        is_student: True
        tea_transformer_width: 768
        vit_paras:
          input_resolution: 224
          patch_size: 32
          width: 768
          layers: 4
          heads: 24
          output_dim: 512
          drop_out: 0
          need_layers: null
    norm: False
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos' ]
    freeze_embed: true
    unfreeze_epoch: 150
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    teacher_need_layers: [ 0, 1, 10, 11 ]
    model_type: 'image'
    warm_steps: 10
    total_steps: 200
    weight_decay: 1.0e-3
    lr: 5.0e-3




data:
  class_path: MainDataModule
  init_args:
    num_workers: 8
    dataset: 'combine_image_dataset'
    dataset_name: 'CombineImageDataset'
    train_batch_size: 1024
    val_batch_size: 1250
    prepare_args:
      raw_data_dir: '/home/pyz/data_tmp'
      teacher_name: 'ViT-B/32'
      overwrite: False
    dataset_args:
      cache_dir: '/data/pyz/.cache'
      combine_dataset_path: '/home/pyz/data_tmp/resize/'
      image_use: [ 'imagenet' ]





trainer:
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  strategy: 'ddp'
  max_epochs: 200
  log_every_n_steps: 1000
  enable_progress_bar: True
  precision: 16
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'imagenet_total_baseline'
      project: 'CLIPDistillation'
      log_model: false
      group: weight_share
      tags: [ 'no-ws', 'test' ]

  callbacks:
    - class_path: LearningRateMonitor
    - class_path: EarlyStopping
      init_args:
        monitor: 'val/loss'
        patience: 15

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_stu_acc/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_loss/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false