model:
  class_path: DistillModel
  init_args:
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'out_kl']
      loss_scale:
        out_l1: 1
        out_cos: 1
        out_kl: 1
      temperature: 1


trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: '/data/pyz/result/Dis_CLIP'
      name: 'weight share-out_kl'
      project: 'ImageDistillation'
      log_model: false
      group: weight_share
      version: 'weight share-out_kl-baseline'
      tags: ['baseline', 'weight share', 'loss change']