trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'l1+cos'
      project: '毕设实验'
      log_model: false
      group: ws_image_encoder
      tags: [ 'ws_image_encoder', 'baseline' ]

model:
  loss_control_para:
    loss_name: [ 'out_cos', 'out_l1' ]
    need_norm: False
