model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model.component.weight_share_model.RepeatTextTransformer
      init_args:
        depth: 4
        repeated_times: 2
        use_transform: True
        compression_embedding: True
        embedding_compression_dim: 256
    loss_control_para:
      loss_name: [ 'out_cos', 'out_l1']
      need_norm: False

    freeze_embed: false
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    teacher_need_layers: [ 0, 1, 10, 11 ]
    model_type: 'text'
    warm_steps: 0.1

    weight_decay: 1.0e-2
    lr: 1.0e-3


data:
  class_path: MainDataModule
  init_args:
    num_workers: 12
    dataset: 'combine_text_dataset'
    dataset_name: 'CombineTextDataset'
    train_batch_size: 1024
    val_batch_size: 625
    prepare_para:
      overwrite: False
      raw_data_dir: '/data/share/pyz/data/'
      text_use: [ 'cc', 'coco' ]
    dataset_para:
      cache_dir: '/data/pyz/.cache'

      teacher_name: 'ViT-B/32'


trainer:
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  accelerator: 'gpu'
  strategy: 'ddp_find_unused_parameters_false'
  max_epochs: 300
  default_root_dir: '/data/pyz/result/L-CLIP/ws_text_dis'


  log_every_n_steps: 100
  enable_progress_bar: True
  check_val_every_n_epoch: 1
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: '/data/pyz/result/L-CLIP/ws_text_dis'
      name: 'text-ws-compression_emb'
      project: 'L-CLIPDistillation'
      log_model: false
      group: text_single

  callbacks:
    - class_path: LearningRateMonitor
#    - class_path: EarlyStopping
#      init_args:
#        monitor: 'val_loss/loss'
#        patience: 40

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_stu_acc/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_loss/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false