model:
  class_path: DistillModel
  init_args:
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'vit_kd']
      vit_kd_para:
        student_dims: 768
        teacher_dims: 768
        low_layers_num: 2
        high_layers_num: 1
trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: '/data/pyz/result/Dis_CLIP'
      name: 'weight share-vit_kd'
      project: 'ImageDistillation'
      log_model: false
      group: weight_share
      version: 'weight share-vit_kd-baseline'
      tags: ['baseline', 'weight share', 'vit_kd-loss']
