model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model.component.resnet_encoder.ModifiedResNet
      init_args:
        layers: [ 1, 2, 5, 1 ]
        output_dim: 512
        heads: 8

    norm: False
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos' ]
      temperature: 1
      normalize: False
    teacher_name: RN101
    download_root: '/data/pyz/.cache'
    warm_steps: 15
    total_steps: 1000
    weight_decay: 1.0e-2
    lr: 1.0e-3

data:
  class_path: MainDataModule
  init_args:
    num_workers: 16
    dataset: 'image_dataset'
    dataset_name: 'ImageDataset'
    train_batch_size: 128
    val_batch_size: 1250
    dataset_para:
      data_dir: '/home/pyz/data_tmp'
      cache_dir: '/data/pyz/data/cache'
      train_image_dir: '/home/pyz/combine_dataset/'
      image_use: [ 'coco' ]
      cache_path: '/data/pyz/.cache/CLIPDistill'
      #      overwrite: True
      teacher_name: RN101


trainer:
  num_sanity_val_steps: 0
  auto_select_gpus: True
  strategy: 'ddp_find_unused_parameters_false'
  default_root_dir: '/data/pyz/result/dis_clip'
  accumulate_grad_batches: 1
  gradient_clip_val: 10
  accelerator: 'gpu'
  devices: [ 6, 7 ]
  max_epochs: 1000
  log_every_n_steps: 30
  enable_progress_bar: True
  check_val_every_n_epoch: 1
  precision: 32
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'resnet'
      project: 'CLIPDistillation'
      log_model: false
      group: resnet

      tags: [ 'baseline', 'resnet' ]


  callbacks:
    - class_path: LearningRateMonitor

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{hp_metric/stu_acc_top1:.3f}-loss{val/loss:.5f}'
        monitor: 'hp_metric/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{hp_metric/stu_acc_top1:.3f}-loss{val/loss:.5f}'
        monitor: 'val/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false