trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name : 'WeightShareDistillation_lr5e-3_all_data'
      project: 'WeightShareDistillation'
      version: null
      log_model: false
      sync_tensorboard: True

model:
  class_path: DistillModel
  init_args:
    lr: 5.0e-3
    student_encoder:
      class_path: model.weight_share_model.RepeatVisionTransformer
      init_args:
        img_size: 224
        patch_size: 32
        in_chans: 3
        out_dim: 512
        embed_dim: 768
        depth: 4
        num_heads: 12
        mlp_ratio: 4.0
        qkv_bias: True
        drop_rate: 0.1
        attn_drop_rate: 0.1
        drop_path_rate: 0.1
        use_cls_token: True
        repeated_times: 2
        use_transform: True

data:
  class_path: DistillationDataModule
  init_args:
    num_workers: 12
    dataset: '_dataset'
    train_batch_size: 1560
    kwargs:
      data_dir: '/data/pyz/data'
      dataset_name: 'ImageDataset'
      cache_dir: '/data/pyz/data/cache'
      train_image_dir: '/home/pyz/combine_dataset/'
      image_use: ['imagenet', 'data_256', 'coco']
      cache_path: '/data/pyz/.cache/CLIPDistill'
      overwrite: False

