model:
  loss_control_para:
    loss_name: [ 'out_l1', 'out_cos' ]
  freeze_embed: false
  norm: false

trainer:
  precision: 32
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'ws-l1-cos-norm'
      project: 'CLIPDistillation'
      log_model: false
      group: weight_share
      tags: [ 'weight share', 'loss change', 'norm' ]