model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model.component.weight_share_model.RepeatVisionTransformer
      init_args:
        img_size: 224
        patch_size: 32
        in_chans: 3
        out_dim: 512
        embed_dim: 768
        depth: 4
        num_heads: 12
        mlp_ratio: 4.0
        qkv_bias: True
        qk_scale: null
        drop_rate: 0.
        attn_drop_rate: 0.
        drop_path_rate: 0.
        hybrid_backbone: null
        rpe_config: null
        repeated_times: 2
        use_transform: True
    norm: False
    loss_control_para:
#LOSSNAME = ['out_l1', 'out_ce', 'out_kl', 'out_cos', 'embedding_mse', 'attention_score_mse',
      #            'attention_probs_mse', 'hidden_rep_mse', 'attention_probs_kl', 'last_value_map_kl',
      #            'vit_kd',
      #            'hard_label', 'soft_label', 'fine_grain', 'logits_mse']
      loss_name: [ 'out_l1', 'out_cos' ]
      temperature: 1
    freeze_embed: true
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    teacher_need_layers: [ 0, 1, 10, 11 ]
    model_type: 'image'
    map_type: 'begin'
    init_type: null
    warm_steps: 15
    total_steps: 300
    weight_decay: 1.0e-2
    lr: 5.0e-4




data:
  class_path: MainDataModule
  init_args:
    num_workers: 8
    dataset: 'image_dataset'
    dataset_name: 'ImageDataset'
    train_batch_size: 1024
    val_batch_size: 1250
    dataset_para:
      data_dir: '/home/pyz/data_tmp'
      cache_dir: '/data/pyz/.cache'
      train_image_dir: '/home/pyz/data_tmp/combine_dataset/'
      image_use: [ 'coco', 'imagenet' ]
      overwrite: False





trainer:
  num_sanity_val_steps: 0
  auto_select_gpus: True
  accumulate_grad_batches: 1
  accelerator: 'gpu'
  devices: [ 4, 5, 6, 7 ]
  strategy: 'ddp_find_unused_parameters_false'
  max_epochs: 300
#  limit_train_batches: 1
  log_every_n_steps: 100
  enable_progress_bar: True
  check_val_every_n_epoch: 1
  precision: 16
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: '/data/pyz/result/Dis_CLIP'
      name: 'baseline-weight share'
      project: 'ImageDistillation'
      log_model: false
      group: weight_share
      # the covered tags should be same length with the tags in share.yaml
  #      tags: ['baseline', 'weight share']
  #      mode: 'online'

  callbacks:
    - class_path: LearningRateMonitor
    #    - class_path: EarlyStopping
    #      init_args:
    #        monitor: 'val/loss'
    #        patience: 15

    - class_path: ModelSummary
      init_args:
        max_depth: 2
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_stu_acc/stu_acc_top1'
        save_last: True
        save_top_k: 2
        mode: 'max'
        auto_insert_metric_name: false
    - class_path: ModelCheckpoint
      init_args:
        filename: '{epoch}-val_acc{val_stu_acc/stu_acc_top1:.3f}-loss{val_loss/loss:.5f}'
        monitor: 'val_loss/loss'
        save_last: True
        save_top_k: 2
        mode: 'min'
        auto_insert_metric_name: false