model:
  class_path: DistillModel
  init_args:
    student_encoder:
      class_path: model._text_encoder.TextEncoder
      init_args:
        transformer_width: 512
        transformer_layers: 2
        transformer_heads: 8
        context_length: 77
        vocab_size: 49408
        embed_dim: 512
        tea_transformer_width: 512
        is_student: True
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    loss_weight: [1.0e4, 1, 10, 1]
    t: 2
trainer:
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: '/data/pyz/result/Dis_CLIP/res'
      name: 'TextEncoder'
      version: 'version_3'
  enable_progress_bar: True
  check_val_every_n_epoch: 1