model:
  class_path: DualDistillModel
  init_args:
    freeze_prefix: [ 'text_encoder' ]
    loss_control_para:
      loss_name: [ 'out_l1', 'out_cos', 'soft_label']
      loss_scale:
        SR: 1


trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name: 'clip_soft_label'
      project: 'CLIPDistillation'
      log_model: false
      group: clip
      tags: [ 'weight share', 'loss change', 'CLIP model' ]