model:
  class_path: DistillModel
  init_args:
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    loss_control_para:
      loss_name: ['l1', 'cos']
    init_type: 'begin'

trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name : 'ImageEncoderBaseLine_l1_cos_16_init_begin'
      project: 'ImageEncoderDistillation'
      version: null
      log_model: false
      sync_tensorboard: True
  precision: 16