trainer:

  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name: 'ws_compression256_tiny'
      project: 'CLIPDistillation'
      log_model: false
      group: ws_text_encoder
      tags: [ 'ws_text_encoder', 'baseline' ]

model:
  student_encoder:
    class_path: model.component.weight_share_model.RepeatTextTransformer
    init_args:
      depth: 2
      repeated_times: 2
      use_transform: True
      compression_embedding: True
  loss_control_para:
    loss_name: [ 'out_l1', 'out_cos' ]
    temperature: 1
    loss_scale:
      out_l1: 1
      out_cos: 1