trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/dis_clip'
      name: 'tiny_bert_image'
      project: '毕设实验'
      log_model: false
      group: ws_image_encoder

model:
  loss_control_para:
    loss_name: [ 'embedding_mse', 'attention_score_mse', 'hidden_rep_mse', 'out_cos' ]
    need_norm: False
  