model:
  class_path: DistillModel
  init_args:
#    init_type: 'mid'
    teacher_name: ViT-B/32
    download_root: '/data/pyz/.cache'
    loss_control_para:
      loss_name: ['last_value_map', 'last_attn']
      loss_scale:
        last_value_map: 1
        last_attn: 3


trainer:
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      dir: '/data/pyz/result/Dis_CLIP'
      name : 'ImageEncoderBaseLine_last_value_attn_prob_16'
      project: 'ImageEncoderDistillation'
      version: null
      log_model: false
      sync_tensorboard: True